name: test_gpu
on: [push]
#  workflow_dispatch:
#  schedule:
#    - cron: '11 11 * * *'
jobs:
  run:
    runs-on: [self-hosted,gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env :
          repo_token: ${{secrets.GITHUB_TOKEN}}
          run: |
            CODEBLOCK="\`\`\`"
            echo $CODEBLOCK > report.md
            nvidia-smi >> report.md
            echo $CODEBLOCK >> report.md
            cml-send-comment report.md
